SF/SF/SF/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('', include('registration.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SF/SF/registration/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import RegisterView, SingInView

urlpatterns = [
    path('registration/', RegisterView.as_view(), name='signup'),
    path('login/', SingInView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(), name='logout')
]

SF/SF/shop/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', ProductListView.as_view(), name='shop_product_list'),
    path('cart/', CartListView.as_view(), name='shop_cart'),
    path('<slug:slug> /', ProductDetailView.as_view(), name='shop_product_detail')
]

SF/SF/shop/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(
        max_length=32,
        verbose_name='название',
        unique=True,
        blank=False,
        null=False,
    )
    slug = models.SlugField(
        verbose_name='URL',
        unique=True,
        blank=False,
        null=False,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(
        max_length=128,
        null=False,
        blank=False,
        verbose_name='название'
    )
    descr = models.CharField(
        max_length=4048,
        verbose_name='описание',
        blank=True,
        null=True,
    )
    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        verbose_name='цена',
        null=False,
        blank=False,
    )
    image = models.ImageField(
        verbose_name='картинка',
        upload_to='product/',
        null=True,
        blank=True,
    )
    slug = models.SlugField(
        verbose_name='URL',
        unique=True,
        blank=True,
        null=True,
    )

    def get_absolute_url(self):
        return reverse('shop_product_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f'Order: {self.pk}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f'Order {self.order} Product {self.product}'

SF/SF/shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from django.shortcuts import render

from .models import Product, OrderItem


class ProductListView(ListView):
    template_name = 'shop/shop.html'
    model = Product
    paginate_by = 3


class ProductDetailView(LoginRequiredMixin, DetailView):
    template_name = 'shop/shop-single.html'
    model = Product
    login_url = '/login/'


class CartListView(LoginRequiredMixin, ListView):
    model = OrderItem
    template_name = 'shop/cart.html'


    def get_queryset(self):
        return self.model.objects.filter(order__is_paid=False)

SF/SF/shop/templates/shop/base.html
{% load static %}
<html lang="en">

      <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">


        <link rel="stylesheet" href="{% static 'css/aos.css' %}">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">

      </head>

      <body>
      {% block content %}
      {% endblock %}

            <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/aos.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>

       </body>

</html>

SF/SF/shop/templates/shop/cart.html
{% extends 'shop/base.html' %}

{% block title %}
CART
{% endblock %}

{% block content %}
  <div class="site-wrap">


    {% include 'shop/components/nav.html' %}

    {% include 'shop/components/breadcrumbs.html' %}

    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <form class="col-md-12" method="post">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="product-thumbnail">Image</th>
                    <th class="product-name">Product</th>
                    <th class="product-price">Price</th>
                    <th class="product-quantity">Quantity</th>
                    <th class="product-total">Total</th>
                    <th class="product-remove">Remove</th>
                  </tr>
                </thead>
                <tbody>

                {% include 'shop/components/product_cart.html' %}

                </tbody>
              </table>
            </div>
          </form>
        </div>
    
        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6 mb-3 mb-md-0">
                <button class="btn btn-primary btn-md btn-block">Update Cart</button>
              </div>
              <div class="col-md-6">
                <button class="btn btn-outline-primary btn-md btn-block">Continue Shopping</button>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <label class="text-black h4" for="coupon">Coupon</label>
                <p>Enter your coupon code if you have one.</p>
              </div>
              <div class="col-md-8 mb-3 mb-md-0">
                <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
              </div>
              <div class="col-md-4">
                <button class="btn btn-primary btn-md px-4">Apply Coupon</button>
              </div>
            </div>
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="col-md-6">
                    <span class="text-black">Subtotal</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">$230.00</strong>
                  </div>
                </div>
                <div class="row mb-5">
                  <div class="col-md-6">
                    <span class="text-black">Total</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">$230.00</strong>
                  </div>
                </div>
    
                <div class="row">
                  <div class="col-md-12">
                    <button class="btn btn-primary btn-lg btn-block" onclick="window.location='checkout.html'">Proceed To
                      Checkout</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-secondary bg-image" style="background-image: url('images/bg_2.jpg');">
      <div class="container">
        <div class="row align-items-stretch">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="banner-1 h-100 d-flex" style="background-image: url('images/bg_1.jpg');">
              <div class="banner-1-inner align-self-center">
                <h2>Pharma Products</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                </p>
              </div>
            </a>
          </div>
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a href="#" class="banner-1 h-100 d-flex" style="background-image: url('images/bg_2.jpg');">
              <div class="banner-1-inner ml-auto  align-self-center">
                <h2>Rated by Experts</h2>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestiae ex ad minus rem odio voluptatem.
                </p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>

{% include 'shop/components/footer.html' %}
{% endblock %}

SF/SF/shop/templates/shop/components/breadcrumbs.html
<div class="bg-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Store</strong></div>
    </div>
  </div>
</div>

SF/SF/shop/templates/shop/components/filters.html
<div class="col-lg-6">
    <h3 class="mb-3 h6 text-uppercase text-black d-block">Filter by Price</h3>
    <div id="slider-range" class="border-primary"></div>
    <input type="text" name="text" id="amount" class="form-control border-0 pl-0 bg-white" disabled="" />
  </div>
  <div class="col-lg-6">
    <h3 class="mb-3 h6 text-uppercase text-black d-block">Filter by Reference</h3>
    <button type="button" class="btn btn-secondary btn-md dropdown-toggle px-4" id="dropdownMenuReference"
      data-toggle="dropdown">Reference</button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
      <a class="dropdown-item" href="#">Relevance</a>
      <a class="dropdown-item" href="#">Name, A to Z</a>
      <a class="dropdown-item" href="#">Name, Z to A</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Price, low to high</a>
      <a class="dropdown-item" href="#">Price, high to low</a>
    </div>
  </div>

SF/SF/shop/templates/shop/components/footer.html
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

        <div class="block-7">
          <h3 class="footer-heading mb-4">About Us</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius quae reiciendis distinctio voluptates
            sed dolorum excepturi iure eaque, aut unde.</p>
        </div>

      </div>
      <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
        <h3 class="footer-heading mb-4">Quick Links</h3>
        <ul class="list-unstyled">
          <li><a href="#">Supplements</a></li>
          <li><a href="#">Vitamins</a></li>
          <li><a href="#">Diet &amp; Nutrition</a></li>
          <li><a href="#">Tea &amp; Coffee</a></li>
        </ul>
      </div>

      <div class="col-md-6 col-lg-3">
        <div class="block-5 mb-5">
          <h3 class="footer-heading mb-4">Contact Info</h3>
          <ul class="list-unstyled">
            <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
            <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
            <li class="email">emailaddress@domain.com</li>
          </ul>
        </div>


      </div>
    </div>
    <div class="row pt-5 mt-5 text-center">
      <div class="col-md-12">
        <p>
          Copyright &copy;
          {% now "Y" %} All rights reserved by <a href="" target="_blank"
            class="text-primary">AnDa</a>
        </p>
      </div>

    </div>
  </div>
</footer>

SF/SF/shop/templates/shop/components/header.html
<div class="site-blocks-cover" style="background-image: url('images/hero_1.jpg');">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
          <div class="site-block-cover-content text-center">
            <h2 class="sub-title">Effective Medicine, New Medicine Everyday</h2>
            <h1>Welcome To Pharma</h1>
            <p>
              <a href="#" class="btn btn-primary px-5 py-3">Shop Now</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section">
    <div class="container">
      <div class="row align-items-stretch section-overlap">
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap bg-primary h-100">
            <a href="#" class="h-100">
              <h5>Free <br> Shipping</h5>
              <p>
                Amet sit amet dolor
                <strong>Lorem, ipsum dolor sit amet consectetur adipisicing.</strong>
              </p>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap h-100">
            <a href="#" class="h-100">
              <h5>Season <br> Sale 50% Off</h5>
              <p>
                Amet sit amet dolor
                <strong>Lorem, ipsum dolor sit amet consectetur adipisicing.</strong>
              </p>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
          <div class="banner-wrap bg-warning h-100">
            <a href="#" class="h-100">
              <h5>Buy <br> A Gift Card</h5>
              <p>
                Amet sit amet dolor
                <strong>Lorem, ipsum dolor sit amet consectetur adipisicing.</strong>
              </p>
            </a>
          </div>
        </div>

      </div>
    </div>
  </div>

SF/SF/shop/templates/shop/components/nav.html
<div class="site-navbar py-2">

   {% include "shop/components/search.html" %}

    <div class="container">
      <div class="d-flex align-items-center justify-content-between">
        <div class="logo">
          <div class="site-logo">
            <a href="index.html" class="js-logo-clone">AnDa</a>
          </div>
        </div>
        <div class="main-nav d-none d-lg-block">
          <nav class="site-navigation text-right text-md-center" role="navigation">
            <ul class="site-menu js-clone-nav d-none d-lg-block">
              <li class="active"><a href="index.html">Home</a></li>
              <li><a href="{% url 'shop_product_list' %}">Store</a></li>
              <li><a href="about.html">About</a></li>
              <li><a href="contact.html">Contact</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Logout</a></li>
              <li><a href="#">{{ user.username }}</a></li>
              {% else %}
              <li><a href="{% url 'signin' %}">Login</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
        <div class="icons">
          <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
          <a href="{% url 'shop_cart' %}" class="icons-btn d-inline-block bag">
            <span class="icon-shopping-bag"></span>
            <span class="number">2</span>
          </a>
          <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
              class="icon-menu"></span></a>
        </div>
      </div>
    </div>
    </div>

SF/SF/shop/templates/shop/components/new_products.html
<div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="title-section text-center col-12">
            <h2 class="text-uppercase">New Products</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 block-3 products-wrap">
            <div class="nonloop-block-3 owl-carousel">

              <div class="text-center item mb-4">
                <a href="shop-single.html"> <img src="images/product_03.png" alt="Image"></a>
                <h3 class="text-dark"><a href="shop-single.html">Umcka Cold Care</a></h3>
                <p class="price">$120.00</p>
              </div>

              {% include shop/components/product_card.html %}

            </div>
          </div>
        </div>
      </div>
    </div>

SF/SF/shop/templates/shop/components/paginator.html
<div class="row mt-5">
  <div class="col-md-12 text-center">
    <div class="site-block-27">
        <ul>
            {% if page_obj.has_previous %}
            <li><a href="?page=1">&lt;&lt;</a></li>
            <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
            {% endif %}

        {% for page in page_obj.paginator %}
            {% if page_obj.number == page.number %}
                <li><a class="active" href="?page={{ page.number }}">{{ page.number }}</a></li>
            {% else %}
                <li><a href="?page={{ page.number }}">{{ page.number }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.number|add:'1' }}">&gt;</a></li>
            <li><a href="?page={{ page_obj.paginator.num_pages }}">&gt;&gt;</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>

SF/SF/shop/templates/shop/components/popular_products.html
<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="title-section text-center col-12">
        <h2 class="text-uppercase">Popular Products</h2>
      </div>
    </div>

    <div class="row">

      {% include shop/components/product_card.html %}

    </div>

    <div class="row mt-5">
      <div class="col-12 text-center">
        <a href="shop.html" class="btn btn-primary px-4 py-3">View All Products</a>
      </div>
    </div>
  </div>
</div>

SF/SF/shop/templates/shop/components/product_card.html
<div class="col-sm-6 col-lg-4 text-center item mb-4">
  <a href="{{ product.get_absolute_url }}"> <img src="{{ product.image.url }}" alt="Image"></a>
  <h3 class="text-dark"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
  <p class="price">${{ product.price }}</p>
</div>

SF/SF/shop/templates/shop/components/product_cart.html
<tr>
    <td class="product-thumbnail">
      <img src="images/product_01.png" alt="Image" class="img-fluid">
    </td>
    <td class="product-name">
      <h2 class="h5 text-black">Bioderma</h2>
    </td>
    <td>$49.00</td>
    <td>
      <div class="input-group mb-3" style="max-width: 120px;">
        <div class="input-group-prepend">
          <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
        </div>
        <input type="text" class="form-control text-center" value="1" placeholder=""
          aria-label="Example text with button addon" aria-describedby="button-addon1">
        <div class="input-group-append">
          <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
        </div>
      </div>

    </td>
    <td>$49.00</td>
    <td><a href="#" class="btn btn-primary height-auto btn-sm">X</a></td>
</tr>

SF/SF/shop/templates/shop/components/search.html
 <div class="search-wrap">
      <div class="container">
        <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
        <form action="#" method="post">
          <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
        </form>
      </div>
 </div>

SF/SF/shop/templates/shop/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Pharma &mdash; Colorlib Template</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
  <link rel="stylesheet" href="fonts/icomoon/style.css">

  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/magnific-popup.css">
  <link rel="stylesheet" href="css/jquery-ui.css">
  <link rel="stylesheet" href="css/owl.carousel.min.css">
  <link rel="stylesheet" href="css/owl.theme.default.min.css">


  <link rel="stylesheet" href="css/aos.css">

  <link rel="stylesheet" href="css/style.css">

</head>

<body>

  <div class="site-wrap">


    <div class="site-navbar py-2">

      <div class="search-wrap">
        <div class="container">
          <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
          <form action="#" method="post">
            <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
          </form>
        </div>
      </div>

      <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="index.html" class="js-logo-clone">Pharma</a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li><a href="index.html">Home</a></li>
                <li><a href="shop.html">Store</a></li>
                <li class="has-children">
                  <a href="#">Dropdown</a>
                  <ul class="dropdown">
                    <li><a href="#">Supplements</a></li>
                    <li class="has-children">
                      <a href="#">Vitamins</a>
                      <ul class="dropdown">
                        <li><a href="#">Supplements</a></li>
                        <li><a href="#">Vitamins</a></li>
                        <li><a href="#">Diet &amp; Nutrition</a></li>
                        <li><a href="#">Tea &amp; Coffee</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Diet &amp; Nutrition</a></li>
                    <li><a href="#">Tea &amp; Coffee</a></li>

                  </ul>
                </li>
                <li><a href="about.html">About</a></li>
                <li class="active"><a href="contact.html">Contact</a></li>
              </ul>
            </nav>
          </div>
          <div class="icons">
            <a href="#" class="icons-btn d-inline-block js-search-open"><span class="icon-search"></span></a>
            <a href="cart.html" class="icons-btn d-inline-block bag">
              <span class="icon-shopping-bag"></span>
              <span class="number">2</span>
            </a>
            <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
                class="icon-menu"></span></a>
          </div>
        </div>
      </div>
    </div>

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0">
            <a href="index.html">Home</a> <span class="mx-2 mb-0">/</span>
            <strong class="text-black">Contact</strong>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2 class="h3 mb-5 text-black">Get In Touch</h2>
          </div>
          <div class="col-md-12">
    
            <form action="#" method="post">
    
              <div class="p-3 p-lg-5 border">
                <div class="form-group row">
                  <div class="col-md-6">
                    <label for="c_fname" class="text-black">First Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="c_fname" name="c_fname">
                  </div>
                  <div class="col-md-6">
                    <label for="c_lname" class="text-black">Last Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="c_lname" name="c_lname">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_email" class="text-black">Email <span class="text-danger">*</span></label>
                    <input type="email" class="form-control" id="c_email" name="c_email" placeholder="">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_subject" class="text-black">Subject </label>
                    <input type="text" class="form-control" id="c_subject" name="c_subject">
                  </div>
                </div>
    
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_message" class="text-black">Message </label>
                    <textarea name="c_message" id="c_message" cols="30" rows="7" class="form-control"></textarea>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-lg-12">
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Send Message">
                  </div>
                </div>
              </div>
            </form>
          </div>
          
        </div>
      </div>
    </div>



    <div class="site-section bg-primary">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <h2 class="text-white mb-4">Offices</h2>
          </div>
          <div class="col-lg-4">
            <div class="p-4 bg-white mb-3 rounded">
              <span class="d-block text-black h6 text-uppercase">New York</span>
              <p class="mb-0">203 Fake St. Mountain View, San Francisco, California, USA</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="p-4 bg-white mb-3 rounded">
              <span class="d-block text-black h6 text-uppercase">London</span>
              <p class="mb-0">203 Fake St. Mountain View, San Francisco, California, USA</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="p-4 bg-white mb-3 rounded">
              <span class="d-block text-black h6 text-uppercase">Canada</span>
              <p class="mb-0">203 Fake St. Mountain View, San Francisco, California, USA</p>
            </div>
          </div>
        </div>
      </div>
      
    </div>


    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

            <div class="block-7">
              <h3 class="footer-heading mb-4">About Us</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius quae reiciendis distinctio voluptates
                sed dolorum excepturi iure eaque, aut unde.</p>
            </div>

          </div>
          <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
            <h3 class="footer-heading mb-4">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="#">Supplements</a></li>
              <li><a href="#">Vitamins</a></li>
              <li><a href="#">Diet &amp; Nutrition</a></li>
              <li><a href="#">Tea &amp; Coffee</a></li>
            </ul>
          </div>

          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
                <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                <li class="email">emailaddress@domain.com</li>
              </ul>
            </div>


          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
              with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank"
                class="text-primary">Colorlib</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>

        </div>
      </div>
    </footer>
  </div>

  <script src="js/jquery-3.3.1.min.js"></script>
  <script src="js/jquery-ui.js"></script>
  <script src="js/popper.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/owl.carousel.min.js"></script>
  <script src="js/jquery.magnific-popup.min.js"></script>
  <script src="js/aos.js"></script>

  <script src="js/main.js"></script>

</body>

</html>

SF/SF/shop/templates/shop/index.html
{% extends "shop/base.html" %}

{% block title %}
HOME
{% endblock %}

{% block content %}

  <div class="site-wrap">


    {% include "shop/components/nav.html %}

    {% include "shop/components/header.html %}

    {% include "shop/components/popular_products.html %}

    {% include "shop/components/new_products.html %}

    {% include "shop/components/footer.html %}

  </div>
{% endblock %}

SF/SF/shop/templates/shop/shop.html
{% extends "shop/base.html" %}

{% block title %}
КРАМА
{% endblock %}

{% block content %}
  <div class="site-wrap">

    {% include "shop/components/nav.html" %}

    {% include "shop/components/breadcrumbs.html" %}

    <div class="site-section">
      <div class="container">
        
        <div class="row">

          {% include "shop/components/filters.html" %}

        </div>

        <div class="row">
          {% for product in product_list %}
           {% include "shop/components/product_card.html" %}
          {% endfor %}
        </div>

           {% include "shop/components/paginator.html" %}

      </div>
    </div>

    {% include "shop/components/footer.html" %}
  </div>
{% endblock %}